modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: [ ]
      valid_status_codes: [ ] 
      method: GET
  tcp_connect:
    prober: tcp
    timeout: 5s 
    tcp:
      preferred_ip_protocol: "ip4"

